abstract: ~
author: 'Mark Lawrence <nomad@null.net>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: GPL
name: SQL-DB
no_index:
  directory:
    - inc
    - t
requires:
  Class::Struct: 0
  Scalar::Util: 0
  perl: 5.8.0
version: 0.02
